// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("GoldenHammer")]
[assembly: AssemblyProductAttribute("GoldenHammer")]
[assembly: AssemblyDescriptionAttribute("Asset compilation pipeline")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "GoldenHammer";
        internal const System.String AssemblyProduct = "GoldenHammer";
        internal const System.String AssemblyDescription = "Asset compilation pipeline";
        internal const System.String AssemblyVersion = "0.1.0.0";
        internal const System.String AssemblyFileVersion = "0.1.0.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
