// <auto-generated/>

using System.Reflection;

[assembly: AssemblyTitle("GoldenHammer")]
[assembly: AssemblyProduct("GoldenHammer")]
[assembly: AssemblyDescription("Asset compilation pipeline")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyConfiguration("Release")]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string AssemblyTitle = "GoldenHammer";
        internal const string AssemblyProduct = "GoldenHammer";
        internal const string AssemblyDescription = "Asset compilation pipeline";
        internal const string AssemblyVersion = "0.1.0.0";
        internal const string AssemblyFileVersion = "0.1.0.0";
        internal const string AssemblyConfiguration = "Release";
    }
}
